# Storytelling Studio Apps deploy action
#
# S2 apps use Google docs and sheets to supply the data they consume. Updating that data
# has meant getting a developer to run a package.json script to save the data to the repo, 
# then either run a bash script to deploy the changes to the CDN or go through normal GitHub 
# pull request workflow to trigger an automated deployment.
#
# There is a want to cut the developer out of the process so that an editor can updata data
# in the Google doc, then select an action from the "Adds-ons" menu to trigger a deployment 
# directly. This action, combined with an add-on script, does just that.

name: Cloud Function Deploy

# Workflow triggered on repository_dispatch event, limited to deploy-project event
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
on:
  repository_dispatch:
    types: [deploy-project]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy_project"
  deploy_project:
    # The type of runner that the job will run on
    runs-on: macos-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{github.event.client_payload.project}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Run deploy command with required env variables for Gootenberg and gsutil
    - name: Run deploy script
      uses: actions-hub/gcloud@master
      env:
        GAPI_CLIENT_EMAIL: ${{secrets.GAPI_CLIENT_EMAIL}}
        GAPI_PRIVATE_KEY: ${{secrets.GAPI_PRIVATE_KEY}}
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_APPLICATION_CREDENTIALS}}
        CLI: gsutil
      with:
        args: npm run deploy:dev


