# Storytelling Studio Apps deploy action
#
# S2 apps use Google docs and sheets to supply the data they consume. Updating that data
# has meant getting a developer to run a package.json script to save the data to the repo, 
# then either run a bash script to deploy the changes to the CDN or go through normal GitHub 
# pull request workflow to trigger an automated deployment.
#
# There is a want to cut the developer out of the process so that an editor can updata data
# in the Google doc, then select an action from the "Adds-ons" menu to trigger a deployment 
# directly. This action, combined with an add-on script, does just that.

name: Cloud Function Deploy

# Workflow triggered on repository_dispatch event, limited to deploy-project event
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
on:
  repository_dispatch:
    types: [deploy-project]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy_project"
  deploy_project:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Use Node 12
    - name: Set Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # repository_dispatch event triggered via the GitHub API:
    # https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
    # POST /repos/:owner/:repo/dispatches
    #  Input
    #  {
    #    "event_type": "deploy-project",
    #    "client_payload": {
    #      "project": "name-of-s2-apps-project"
    #    }
    #  }


    # Run shell script
    - name: Run deploy script
      run: sh ./${{github.event.client_payload.project}}/test.sh
